version: "3.9"

networks:
  wireos-net:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
    env_file: .env
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - wireos-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - wireos-net